export const FETCHING_CONTACTS = 'FETCHING_CONTACTS'
export const FETCHING_CONTACTS_SUCCESS = 'FETCHING_CONTACTS_SUCCESS'
export const FETCHING_CONTACTS_FAILURE = 'FETCHING_CONTACTS_FAILURE'
export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE';
export const SEARCH_BAR = 'SEARCH_BAR';
export const SEARCH_LIST = 'SEARCH_LIST';
export const CLEAR_SEARCH_BAR = 'CLEAR_SEARCH_BAR';
export const SELECT_CONTACT = 'SELECT_CONTACT';
export const DESELECT_CONTACT = 'DESELECT_CONTACT';
export const SELECT_CHAT = 'SELECT_CHAT';
export const DESELECT_CHAT = 'DESELECT_CHAT';
export const ADD_SELECTOR = 'ADD_SELECTOR';
export const SELECTED_CONTACTS = 'SELECTED_CONTACTS';
export const SELECT_IN_CONTACTS = 'SELECT_IN_CONTACTS';


export const LOGINING = 'LOGINING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const IS_SIGNED_IN = 'IS_SIGNED_IN';
export const INIT_APPLICATION = 'INIT_APPLICATION';

export const OVERLAY_VISIBLE = 'OVERLAY_VISIBLE';

