// Contacts actions and reducer constants

export const FETCHING_CONTACTS = 'FETCHING_CONTACTS'
export const FETCHING_CONTACTS_SUCCESS = 'FETCHING_CONTACTS_SUCCESS'
export const FETCHING_CONTACTS_FAILURE = 'FETCHING_CONTACTS_FAILURE'
export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE';
export const SEARCH_BAR = 'SEARCH_BAR';
export const SEARCH_LIST = 'SEARCH_LIST';
export const CLEAR_SEARCH_BAR = 'CLEAR_SEARCH_BAR';
export const SELECT_CONTACT = 'SELECT_CONTACT';
export const DESELECT_CONTACT = 'DESELECT_CONTACT';
export const SELECT_CHAT = 'SELECT_CHAT';
export const DESELECT_CHAT = 'DESELECT_CHAT';
export const ADD_SELECTOR = 'ADD_SELECTOR';
export const SELECTED_CONTACTS = 'SELECTED_CONTACTS';
export const SELECT_IN_CONTACTS = 'SELECT_IN_CONTACTS';
export const SAVE_MY_USERNAME = 'SAVE_MY_USERNAME';
export const SAVE_MY_USER_ID = 'SAVE_MY_USER_ID';
export const SET_MY_PROFILE = 'SET_MY_PROFILE';
export const FETCHING_CONTACT = 'FETCHING_CONTACT'
export const FETCHING_CONTACT_SUCCESS = 'FETCHING_CONTACT_SUCCESS'
export const FETCHING_CONTACT_FAILURE = 'FETCHING_CONTACT_FAILURE'

// Login actions and reducer constants

export const LOGINING = 'LOGINING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const IS_SIGNED_IN = 'IS_SIGNED_IN';
export const INIT_APPLICATION = 'INIT_APPLICATION';

// Overlay actions and reducer constants

export const OVERLAY_VISIBLE = 'OVERLAY_VISIBLE';

// AppState actions and reducer constants

export const SET_NIGHT_THEME = 'SET_NIGHT_THEME';
export const SET_LIGHT_THEME = 'SET_LIGHT_THEME';
export const NOTIFICATIONS = 'NOTIFICATIONS';
export const CHAT_BACKGROUND = 'CHAT_BACKGROUND';
export const TEXT_SIZE = 'TEXT_SIZE';

// Chat actions and reducer constants

export const SET_ROOM_ID = 'SET_ROOM_ID';
export const SET_END = 'SET_END';
export const SET_START = 'SET_START';
export const GET_MESSAGE_HISTORY = 'GET_MESSAGE_HISTORY';
export const GET_MESSAGE_HISTORY_SUCCESS = 'GET_MESSAGE_HISTORY_SUCCESS';
export const GET_MESSAGE_HISTORY_FAILURE = 'GET_MESSAGE_HISTORY_FAILURE';
export const GET_UPDATED_MESSAGE_HISTORY = 'GET_UPDATED_MESSAGE_HISTORY';
export const UPDATE_MESSAGE_HISTORY = 'UPDATE_MESSAGE_HISTORY';
export const PUSH_NEW_MESSAGE = 'PUSH_NEW_MESSAGE';
export const PUSH_NEW_MESSAGE_SUCCESS = 'PUSH_NEW_MESSAGE_SUCCESS';
export const PUSH_NEW_MESSAGE_FAILURE = 'PUSH_NEW_MESSAGE_FAILURE';
export const HANDLE_MESSAGE_CHANGE = 'HANDLE_MESSAGE_CHANGE';
export const PUSH_NEW_MESSAGE_TO_HISTORY = 'PUSH_NEW_MESSAGE_TO_HISTORY';
export const RESET_NEW_MESSAGE = 'RESET_NEW_MESSAGE';
export const NEW_MESSAGE = 'NEW_MESSAGE'

// P2Chat actions and reducer constants

export const GET_ALL_TOPICS = 'GET_ALL_TOPICS';
export const GET_TOPIC = 'GET_TOPIC';
export const NEW_TOPIC = 'NEW_TOPIC';
export const ADD_TOPIC_TO_ARRAY = 'ADD_TOPIC_TO_ARRAY';
export const GET_MATCHES = 'GET_MATCHES';

export const GET_ALL_P2CHATS = 'GET_ALL_P2CHATS';
export const GET_ALL_P2CHATS_FAILURE = 'GET_ALL_P2CHATS_FAILURE';
export const GET_ALL_P2CHATS_SUCCESS = 'GET_ALL_P2CHATS_SUCCESS';
export const GET_CHAT_MEMBERS = 'GET_CHAT_MEMBERS';
export const HANDLE_P2CHAT_MESSAGE_CHANGE = 'HANDLE_P2CHAT_MESSAGE_CHANGE';

export const SET_END_P2CHAT = 'SET_END_P2CHAT';
export const SET_START_P2CHAT = 'SET_START_P2CHAT';
export const GET_P2CHAT_MESSAGE_HISTORY = 'GET_P2CHAT_MESSAGE_HISTORY';
export const GET_P2CHAT_MESSAGE_HISTORY_FAILURE = 'GET_P2CHAT_MESSAGE_HISTORY_FAILURE';
export const GET_P2CHAT_MESSAGE_HISTORY_SUCCESS = 'GET_P2CHAT_MESSAGE_HISTORY_SUCCESS';
export const GET_P2CHAT_UPDATED_MESSAGE_HISTORY = 'GET_P2CHAT_UPDATED_MESSAGE_HISTORY';
