export const FETCHING_CONTACTS = 'FETCHING_CONTACTS'
export const FETCHING_CONTACTS_SUCCESS = 'FETCHING_CONTACTS_SUCCESS'
export const FETCHING_CONTACTS_FAILURE = 'FETCHING_CONTACTS_FAILURE'
export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE';

export const LOGINING = 'LOGINING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const IS_SIGNED_IN = 'IS_SIGNED_IN';
export const INIT_APPLICATION = 'INIT_APPLICATION';

export const OVERLAY_VISIBLE = 'OVERLAY_VISIBLE';

